# Blog info
blog_name: VIP FE @ SH
slogan: eat more, sleep more, code more
url: http://vip-fe-sh.com

# Set avatar (Absolute url and relative url)
avatar: http://7xpbfd.com1.z0.glb.clouddn.com/space.png

# Set favicon
favicon: http://7xpbfd.com1.z0.glb.clouddn.com/imgfavicon.ico

# For seo
keywords: 前端,前端开发,用户体验,frontend,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives/
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: false
  - name: Github
    url: https://github.com/vip-fe-sh
    target_blank: true #在新页面打开
  - name: About
    url: /about/
    target_blank: false

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
# google_analytics:
baidu_analytics: 4ba5df6accad3864f0516e6b4262eeae

# Comment service
# disqus_shortname:
duoshuo_shortname: vip-fe-sh


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "VIP FE @ SH"
    - "前端开发，HTML / CSS / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@vip-fe-sh"
    text_value_url: https://github.com/vip-fe-sh
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@ppxu"
    text_value_url: http://weibo.com/ppxu
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "xyang0110@gmail.com"
  - type: location
    icon: icon-location
    text_value: 上海

project:
  - type: company
    name: vip-cli
    url: https://github.com/vip-fe-sh/vip-cli
    intro: A simple CLI for scaffolding Vue.js projects in VIP
  - type: company
    name: template-vips
    url: https://github.com/vip-fe-sh/template-vips
    intro: A full-featured Webpack setup with hot-reload, lint-on-save, resource fetch & css extraction
